- hosts: Elk
  user: jtenriquez
  become: yes
  gather_facts: no
  pre_tasks:
    - name: "repository"
      raw: 'apt update'
    - name: "Install python"
      raw: 'apt install -y python'
    - name: "Install aptitude"
      raw: 'apt install -y aptitude'
    - name: "Install python-apt"
      raw: 'apt install -y python-apt'

- hosts: Elk
  user: jtenriquez
  become: yes
  roles:
    - install_prometheus
    - install_influxdb
    - install_grafana
