---
- name: Instalando dependency Prometheus
  apt:
    name: ["wget", "tar", "git"]
    state: latest
    update_cache: yes

- name:  group prometheus
  group:
    name: prometheus
    state: present

- name: user  prometheus
  user:
    name: prometheus
    group: prometheus
    shell: /bin/false
    system: yes

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.15.1/prometheus-2.15.1.linux-amd64.tar.gz"
    dest: "/opt/"
    mode: "0755"
    owner: prometheus
    group: prometheus
 
- name: Extract tar.gz prometheus
  unarchive:
    src: "/opt/prometheus-2.15.1.linux-amd64.tar.gz"
    dest: "/opt/"
    mode: "0755"
    owner: prometheus
    group: prometheus
    remote_src: yes


- name: directory /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    mode: "0755"
    owner: prometheus
    group: prometheus


- name: directory /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    mode: "0755"
    owner: prometheus
    group: prometheus


- name: dirrctory /var/log/prometheus
  file:
    path: /var/log/prometheus
    state: directory
    mode: "0755"
    owner: prometheus
    group: prometheus

- name: Move prometheus
  file:
    src: "/opt/prometheus/prometheus"
    dest: "/usr/local/bin/prometheus"
    mode: "0777"
    owner: prometheus
    group: prometheus
    state: hard

- name: Move promtool
  file:
    src: "/opt/prometheus/promtool"
    dest: "/usr/local/bin/promtool"
    mode: "0777"
    owner: prometheus
    group: prometheus
    state: hard

- name: Copy console_libraries
  copy:
    src: "/opt/prometheus/console_libraries"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes

- name: Copy consoles
  copy:
    src: "/opt/prometheus/consoles"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: "0755"
    remote_src: yes


- name: Copy config
  template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: "0755"


- name:  systemd prometheus
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/prometheus.service"
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Enable prometheus.service
  systemd:
    name: prometheus
    enabled: yes


- name: Start prometheus.service
  systemd:
    name: prometheus
    state: started
    daemon_reload: yes
