---
# tasks file for install_grafana
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest


- name: key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install grafana
  apt:
    update_cache: yes
    name: grafana
    state: latest

- name: Enable grafana
  systemd:
    enabled: yes
    name: grafana-server

- name: Start grafana
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
